/* eslint-disable @typescript-eslint/no-require-imports */
const {spawn}=require('node:child_process');const fs=require('node:fs');const assert=require('node:assert/strict');
const server=spawn(process.execPath,['node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','--port','3113'],{cwd:process.cwd(),stdio:['ignore','pipe','pipe']});
const chrome=spawn('/usr/bin/google-chrome',['--headless','--no-sandbox','--disable-dev-shm-usage','--disable-background-networking','--no-first-run','--no-default-browser-check','--remote-debugging-port=9233','--user-data-dir=/tmp/kalend-block3-browser-profile','about:blank'],{stdio:'ignore'});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));let socket;
async function waitUrl(url){for(let i=0;i<120;i++){try{const r=await fetch(url);if(r.ok)return r;}catch{}await sleep(250);}throw Error('Server/browser did not start');}
(async()=>{
 await waitUrl('http://127.0.0.1:3113/planos');const targets=await(await waitUrl('http://127.0.0.1:9233/json')).json();socket=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>socket.addEventListener('open',r,{once:true}));
 let seq=0;const pending=new Map(),errors=[];socket.addEventListener('message',event=>{const msg=JSON.parse(event.data);if(msg.id){const cb=pending.get(msg.id);pending.delete(msg.id);if(msg.error)cb.reject(Error(JSON.stringify(msg.error)));else cb.resolve(msg.result);}if(msg.method==='Runtime.exceptionThrown')errors.push(msg.params.exceptionDetails.exception?.description||msg.params.exceptionDetails.text);});
 const call=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}));});
 const evaluate=async expression=>{const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;};
 await call('Page.enable');await call('Runtime.enable');await call('Page.bringToFront');
 const fixture=`
 const realFetch=window.fetch.bind(window);const q=new URLSearchParams(location.search);const role=q.get('fixture-role')||'OWNER';
 window.__profile={user:{id:'notification-user',name:'Maria Silva',email:'maria@example.invalid',isSuperAdmin:role==='SUPER_ADMIN'},systemRole:role==='SUPER_ADMIN'?'SUPER_ADMIN':'USER',selectedCompanyId:role==='SUPER_ADMIN'?null:'company-a',memberships:role==='SUPER_ADMIN'?[]:['a','b'].map(id=>({id:'membership-'+id,role,company:{id:'company-'+id,name:'Empresa '+id.toUpperCase(),slug:id,status:'ACTIVE',isActive:true}})),session:{expiresAt:'2030-01-01T00:00:00Z',refreshExpiresAt:'2030-01-02T00:00:00Z'}};
 window.__calls=[];window.__failList=false;window.__failRead=false;window.__expired=q.has('expired');window.__delay=0;window.__preference=true;
 window.__items=Array.from({length:25},(_,i)=>({id:'notification-'+i,type:i===0?'pagamento':'sistema',title:i===0?'Pagamento recebido':'Atualização '+i,message:i===0?'Mensagem longa para verificar quebra de texto em qualquer largura. '+('Informação do sistema. '.repeat(4)):'Uma atualização está disponível.',scope:i===1?'GLOBAL':'COMPANY',companyId:i===1?null:window.__profile.selectedCompanyId,company:i===1?null:{name:'Empresa A'},createdAt:'2026-10-02T10:00:00Z',expiresAt:'2026-10-09T10:00:00Z',readAt:i>22?'2026-10-02T11:00:00Z':null,actionUrl:i===0?'/conta':null,actionLabel:i===0?'Ver minha conta':null}));
 if(role==='SUPER_ADMIN')window.__items=window.__items.map(n=>({...n,scope:'GLOBAL',companyId:null,company:null}));
 window.fetch=async(input,init={})=>{const url=new URL(typeof input==='string'?input:input.url,location.href);if(url.hostname!=='api.kalend.invalid')return realFetch(input,init);const path=url.pathname;window.__calls.push({path,query:url.search,method:init.method||'GET',body:init.body});let data={},status=200;
 if(path==='/auth/me'){data=window.__profile;if(window.__expired)status=401;}
 else if(path==='/auth/refresh')status=401;
 else if(path==='/auth/logout'){window.__expired=true;data={ok:true};}
 else if(path==='/notifications/unread-count')data={unreadCount:window.__items.filter(n=>!n.readAt).length,companyId:window.__profile.selectedCompanyId,serverNow:'2026-10-02T12:00:00Z'};
 else if(path==='/notifications/preferences'){if(init.method==='PUT')window.__preference=JSON.parse(init.body).inSystemEnabled;data={inSystemEnabled:window.__preference};}
 else if(path==='/notifications'){if(window.__delay)await new Promise(r=>setTimeout(r,window.__delay));if(window.__failList)status=503;const filter=url.searchParams.get('filter'),offset=Number(url.searchParams.get('cursor')||0),limit=Number(url.searchParams.get('limit')||20);const rows=window.__items.filter(n=>filter==='unread'?!n.readAt:filter==='read'?!!n.readAt:true);data={items:rows.slice(offset,offset+limit),nextCursor:offset+limit<rows.length?String(offset+limit):null,companyId:window.__profile.selectedCompanyId,serverNow:'2026-10-02T12:00:00Z'};}
 else if(path==='/notifications/read-all'||/^\\/notifications\\/[^/]+\\/read$/.test(path)){if(window.__failRead)status=503;else window.__items=window.__items.map(n=>path.endsWith('/read-all')||path.split('/')[2]===n.id?{...n,readAt:'2026-10-02T12:00:00Z'}:n);data={updated:1,companyId:window.__profile.selectedCompanyId,serverNow:'2026-10-02T12:00:00Z'};}
 else if(path==='/company/billing/regularization')data={serverNow:'2026-10-02T12:00:00Z',trial:{active:false,endsAt:null,remainingDays:0,expired:false},financial:{requiresAction:false,status:null},context:{companyId:window.__profile.selectedCompanyId,role},subscription:null,checkout:{available:false,gateways:[],limitation:null},pendingCheckout:null};
 else if(path==='/communication/push/public-config')data={available:false,publicKey:null,environment:null};
 else if(path==='/communication/push/subscriptions')data=[];
 return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json'}});};`;
 await call('Page.addScriptToEvaluateOnNewDocument',{source:fixture});
 async function navigate(path){await call('Page.navigate',{url:'http://127.0.0.1:3113'+path});await sleep(450);await call('Page.bringToFront');await sleep(100);}
 async function press(key,code=key,modifiers=0){await call('Input.dispatchKeyEvent',{type:'keyDown',key,code,modifiers,...(key==='Enter'?{text:'\r',unmodifiedText:'\r'}:{}),windowsVirtualKeyCode:({Escape:27,Tab:9,Enter:13,Space:32})[code]});await call('Input.dispatchKeyEvent',{type:'keyUp',key,code,modifiers,windowsVirtualKeyCode:({Escape:27,Tab:9,Enter:13,Space:32})[code]});await sleep(50);}
 async function clickText(selector,text){await evaluate(`[...document.querySelectorAll(${JSON.stringify(selector)})].find(e=>e.textContent.trim()===${JSON.stringify(text)}).click()`);await sleep(160);}
 const results=[];const widths=[360,375,390,414,768,1024,1280,1440,1920];
 for(const role of (process.env.KALEND_INTERACTIONS_ONLY?[]:['SUPER_ADMIN','OWNER','ADMIN','PROFESSIONAL','RECEPTIONIST','CLIENT'])){
  await navigate('/conta/notificacoes?fixture-role='+role);
  assert.equal(await evaluate("document.querySelector('h1').textContent"),'Notificações');
  assert.equal(await evaluate("document.querySelectorAll('.k-admin-header').length"),1);
  for(const width of widths){await call('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:false});for(const theme of ['dark','light']){
   await evaluate(`document.documentElement.dataset.theme='${theme}';window.dispatchEvent(new Event('kalend:theme'))`);await sleep(20);
   const measure=await evaluate("({scrollWidth:document.documentElement.scrollWidth,headerHeight:document.querySelector('.k-admin-header').getBoundingClientRect().height,clipped:[...document.querySelectorAll('.k-admin-header button,.k-admin-header a,.k-account-page button')].filter(e=>{const r=e.getBoundingClientRect();return r.width>0&&(r.left<0||r.right>innerWidth+1)}).map(e=>e.textContent)})");results.push({role,width,theme,view:'center',...measure});
   await evaluate("document.querySelector('.k-notification-bell').click()");await sleep(100);
   const panel=await evaluate("(()=>{const d=document.querySelector('#notification-panel'),r=d.getBoundingClientRect();return{scrollWidth:document.documentElement.scrollWidth,panelLeft:r.left,panelRight:r.right,panelScroll:d.scrollWidth,panelWidth:d.clientWidth,focusInside:d.contains(document.activeElement),footerVisible:(()=>{const a=d.querySelector('a[href=\"/conta/notificacoes\"]'),b=a.getBoundingClientRect();return b.top>=r.top&&b.bottom<=r.bottom;})(),headerHeight:document.querySelector('.k-admin-header').getBoundingClientRect().height,clipped:[]}})()");results.push({role,width,theme,view:'panel',...panel});
   await press('Escape');assert.equal(await evaluate("document.activeElement.classList.contains('k-notification-bell')"),true);
  }}console.log('validated notifications role',role);
 }
 await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:false});await navigate('/conta/notificacoes?fixture-role=OWNER');
 assert.equal(await evaluate("document.querySelector('.k-notification-badge').textContent"),'23');
 await evaluate("document.querySelector('.k-notification-bell').focus()");await sleep(100);await press('Enter');assert.equal(await evaluate("document.querySelector('#notification-panel').open"),true);assert.equal(await evaluate("document.activeElement.getAttribute('aria-label')"),'Fechar notificações');
 await press('Tab','Tab',8);assert.equal(await evaluate("document.activeElement.getAttribute('href')"),'/conta/notificacoes#preferencias');await press('Tab');assert.equal(await evaluate("document.activeElement.getAttribute('aria-label')"),'Fechar notificações');await press('Escape');
 await evaluate("document.querySelector('.k-notification-bell').focus()");await press(' ','Space');assert.equal(await evaluate("document.querySelector('#notification-panel').open"),true);await press('Escape');
 await clickText('.k-account-page button','Carregar mais');assert.equal(await evaluate("document.querySelectorAll('.k-account-page .k-notification-item').length"),25);
 await clickText('.k-account-page button','Lidas');assert.equal(await evaluate("document.querySelectorAll('.k-account-page .k-notification-item').length"),2);
 await clickText('.k-account-page button','Não lidas');assert.equal(await evaluate("document.querySelectorAll('.k-account-page .k-notification-item').length"),20);
 await evaluate("window.__failRead=true;document.querySelector('.k-account-page button[aria-label^=\"Marcar como lida:\"]').click()");await sleep(150);assert.equal(await evaluate("!!document.querySelector('.k-account-page [role=alert]')"),true);assert.equal(await evaluate("window.__items[0].readAt"),null);
 await evaluate("window.__failRead=false;document.querySelector('.k-account-page button[aria-label^=\"Marcar como lida:\"]').click()");await sleep(200);assert.equal(await evaluate("document.querySelector('.k-notification-badge').textContent"),'22');
 await clickText('.k-account-page button','Marcar todas como lidas');assert.equal(await evaluate("!!document.querySelector('.k-notification-badge')"),false);assert.equal(await evaluate("document.querySelector('.k-account-page').innerText.includes('Você está em dia.')"),true);
 await evaluate("window.__failList=true");await clickText('.k-account-page button','Atualizar');assert.equal(await evaluate("document.querySelector('.k-account-page').innerText.includes('Não foi possível carregar suas notificações.')"),true);
 await evaluate("window.__failList=false");await clickText('.k-account-page button','Tentar novamente');assert.equal(await evaluate("!!document.querySelector('.k-account-page [role=alert]')"),false);
 await evaluate("window.__delay=600;[...document.querySelectorAll('.k-account-page button')].find(e=>e.textContent==='Atualizar').click()");await sleep(70);assert.equal(await evaluate("document.querySelector('.k-account-page').innerText.includes('Carregando notificações')"),true);await sleep(700);await evaluate("window.__delay=0");
 await clickText('#preferencias button','Desativar notificações no sistema');assert.equal(await evaluate('window.__preference'),false);await clickText('#preferencias button','Ativar notificações no sistema');assert.equal(await evaluate('window.__preference'),true);
 await evaluate("window.__profile={...window.__profile,selectedCompanyId:'company-b'};window.__items=[{...window.__items[0],id:'new-company-notification',title:'Empresa B',companyId:'company-b',company:{name:'Empresa B'},readAt:null}];window.dispatchEvent(new Event('kalend:tenant-changed'))");await sleep(300);
 assert.equal(await evaluate("document.querySelector('.k-notification-badge').textContent"),'1');assert.equal(await evaluate("document.querySelector('.k-account-page .k-notification-title').textContent"),'Empresa B');
 await evaluate("window.__expired=true;window.dispatchEvent(new Event('focus'))");await sleep(250);assert.equal(await evaluate("!!document.querySelector('.k-notification-bell')"),false);
 await navigate('/conta/notificacoes?fixture-role=CLIENT');await evaluate("document.querySelector('.k-admin-header button[aria-label=\"Sair\"]').click()");await sleep(250);assert.equal(await evaluate('location.pathname'),'/');assert.equal(await evaluate("!!document.querySelector('.k-notification-bell')"),false);
 await navigate('/conta/notificacoes?fixture-role=SUPER_ADMIN');await evaluate("document.documentElement.dataset.theme='dark'");await sleep(80);
 const shot=await call('Page.captureScreenshot',{format:'png'});fs.writeFileSync('/tmp/kalend-block3-center-390.png',Buffer.from(shot.data,'base64'));await evaluate("document.querySelector('.k-notification-bell').click()");await sleep(100);const panelShot=await call('Page.captureScreenshot',{format:'png'});fs.writeFileSync('/tmp/kalend-block3-panel-390.png',Buffer.from(panelShot.data,'base64'));
 const failures=results.filter(r=>r.scrollWidth>r.width+1||r.headerHeight>80||r.clipped.length||(r.view==='panel'&&(r.panelLeft<0||r.panelRight>r.width+1||r.panelScroll>r.panelWidth+1||!r.focusInside||!r.footerVisible)));
 fs.writeFileSync('/tmp/kalend-block3-browser.json',JSON.stringify({fixtureOnly:true,results,failures,errors,interactionChecks:'Enter/Space/Escape/focus trapping, read/error/retry, read all/count, pagination/filters/loading, preferences, tenant switch, expired session, logout'},null,2));console.log(JSON.stringify({checks:results.length,failures,errors},null,2));if(failures.length||errors.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>{socket?.close();chrome.kill('SIGTERM');server.kill('SIGTERM');});
