"use client";
import Link from "next/link";
import { annualAvailable, annualSaving, planLimit, planLimits, type BillingInterval } from "@/lib/plan-presentation";
import type { PublicPlan } from "@/lib/contracts";
import { money } from "@/lib/commercial";
import { Badge } from "@/components/ui/badge";
import { EmptyState } from "@/components/ui/empty-state";

export function PlanCatalog({ plans, interval, onInterval, selectedId, onSelect, disabled = false }: { plans: PublicPlan[]; interval: BillingInterval; onInterval: (value: BillingInterval) => void; selectedId?: string; onSelect?: (plan: PublicPlan) => void; disabled?: boolean }) {
  const annual = plans.some(annualAvailable);
  const features = Array.from(new Set(plans.flatMap(plan => plan.features.filter(feature => feature.enabled).map(feature => feature.name))));
  return <div className="k-catalog"><fieldset className="k-interval" disabled={disabled}><legend>Período de cobrança</legend><label><input type="radio" name="billing-interval" checked={interval === "MONTHLY"} onChange={() => onInterval("MONTHLY")} />Mensal</label>{annual && <label><input type="radio" name="billing-interval" checked={interval === "YEARLY"} onChange={() => onInterval("YEARLY")} />Anual</label>}</fieldset>
    {!plans.length ? <EmptyState title="Nenhum plano publicado no momento">Volte mais tarde para consultar o catálogo.</EmptyState> : <><div className="k-plan-grid" id="catalogo">{plans.map(plan => {
      const hasAnnual = annualAvailable(plan);
      const price = interval === "YEARLY" ? hasAnnual ? plan.yearlyPriceCents : null : plan.monthlyPriceCents;
      const saving = interval === "YEARLY" ? annualSaving(plan) : null;
      return <article key={plan.id} className={`k-card k-plan ${plan.isFeatured ? "k-plan-featured" : ""} ${selectedId === plan.id ? "k-plan-selected" : ""}`}><div className="k-actions">{plan.isFeatured && <Badge tone="primary">{plan.badge || "Destaque"}</Badge>}{!plan.isFeatured && plan.badge && <Badge>{plan.badge}</Badge>}</div><h3>{plan.name}</h3>{plan.description && <p>{plan.description}</p>}<div className="k-plan-price">{price !== null && price > 0 ? <><strong>{money(price)}</strong><span> / {interval === "YEARLY" ? "ano" : "mês"}</span></> : <strong>{interval === "YEARLY" && !hasAnnual ? "Anual indisponível" : "Preço não disponível para compra"}</strong>}</div>{interval === "YEARLY" && hasAnnual && <p className="k-muted">Equivalente a {money(plan.yearlyPriceCents! / 12)} por mês, com cobrança anual de {money(plan.yearlyPriceCents!)}.</p>}{saving && <Badge tone="success">Economia de {money(saving.cents)} por ano{saving.percent > 0 ? ` (${saving.percent}%)` : ""}</Badge>}{plan.trialEnabled && plan.trialDays > 0 && <p>Teste disponível: {plan.trialDays} dias, conforme elegibilidade.</p>}<ul className="k-plan-features">{plan.features.filter(feature => feature.enabled).map(feature => <li key={feature.id}>{feature.name}</li>)}</ul><dl className="k-plan-limits">{planLimits.map(([label,key]) => <div key={key}><dt>{label}</dt><dd>{planLimit(plan[key])}</dd></div>)}</dl>{onSelect ? <label className="k-plan-choice"><input type="radio" name="plan" value={plan.id} checked={selectedId === plan.id} disabled={disabled || price === null || price <= 0} onChange={() => onSelect(plan)} /><span>{selectedId === plan.id ? "Plano selecionado" : "Escolher plano"}</span></label> : <Link className="k-link-button" href="/conta/planos">Escolher {plan.name}</Link>}</article>;
    })}</div><section className="k-section k-comparison"><h2>Compare os planos</h2><div className="k-table-scroll k-comparison-desktop" role="region" aria-label="Comparação de planos" tabIndex={0}><table><caption>Recursos e limites publicados no catálogo</caption><thead><tr><th scope="col">Recurso</th>{plans.map(plan => <th scope="col" key={plan.id}>{plan.name}</th>)}</tr></thead><tbody>{planLimits.map(([label,key]) => <tr key={key}><th scope="row">{label}</th>{plans.map(plan => <td key={plan.id}>{planLimit(plan[key])}</td>)}</tr>)}{features.map(name => <tr key={name}><th scope="row">{name}</th>{plans.map(plan => <td key={plan.id}>{plan.features.some(feature => feature.enabled && feature.name === name) ? "Incluído" : "Não incluído"}</td>)}</tr>)}</tbody></table></div><div className="k-comparison-mobile">{features.map(name => <div className="k-card" key={name}><h3>{name}</h3><dl>{plans.map(plan => <div key={plan.id}><dt>{plan.name}</dt><dd>{plan.features.some(feature => feature.enabled && feature.name === name) ? "Incluído" : "Não incluído"}</dd></div>)}</dl></div>)}<p>Os limites de cada plano estão detalhados nos cards acima.</p></div></section></>}
  </div>;
}
